---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
</script>
```

<!-- place activity 1 here -->

Although a sequential optimization generally is effective, it often is not efficient because it adjusts only one factor at a time. A more efficient algorithm adjusts all factors at the same time, moving in the direction that provides the greatest change (steepest ascent) in the response.

The controls on the right are identical to those on the previous tab with the exception that the optimization path is always shown superimposed on either a contour plot (in 2D) or a surface plot (in 3D).

**Exercise 1**. Leave the default conditions in place: example 1; initial factor levels of (0,0); and a display that shows the path overlayed on a contour plot. Explain how you can tell that the path to the maximum response at (3,7) is a steepest ascent optimization and not a sequential optimization.

**Exercise 2**. Select the second example and adjust the initial factor levels so that (A,B) = (10,0). Set the display to show a contour plot in 2D. How many steps does it take to reach the optimum response? Set up the same optimization using the tab for a sequential optimization, and determine how many steps it takes to reach the optimum response. Explain why the two algorithms take such different pathways and have such different efficiencies. 

**Exercise 3**. Use this tab and the previous tab to explore the relative efficiencies of these two algorithms for all four examples. Are there shapes of response surfaces and/or locations of initial starting points where their efficiencies are similar? Are there shapes of response surfaces and/or location of initial starting points where their efficiencies are different? 
