---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
</script>
```

<!-- place activity 1 here -->

In a sequential optimization, we begin with the response for a single set of factor levels and measure the response as we change the level of one factor (A) while holding constant the level of the other factor (B). When the response no longer improves, we switch, holding the first factor constant and monitoring the response as we change the second factor's level. We continue this pattern until a change in either factor's level does not increase the response.

Use the controls on the upper right to explore the sequential optimization for four examples of two-factor response surfaces. The upper set of sliders gives the initial levels for factor A and for factor B. The two sets of radio buttons provide access to four ways to visualize the optimization's path, which begins with the large filled circle and extends in a series of steps shown by line segments and small open circles. The lower set of sliders rotates and tilts the 3D plots. In all cases, factor A is optimized first.

**Exercise 1**. Leave the default conditions in place: example 1; initial factor levels of (0,0); and a display that shows the path only in 2D. Record the position of the optimum response. Set the display to path only in 3D and compare the 2D and 3D views to each other. What additional information is available from the 3D view? Change the initial factor levels to (10,0), (0,10), (10,10), and (5,5). Is the algorithm's optimum response sensitive to the choice of initial factor levels? You may wish to explore a few additional initial factor levels. Repeat for the other three examples.

**Exercise 2**. Look over your data from Question 1 and, for each example, describe, as best you can, the shape of its response surface based on the paths taken during the optimization. When you are done, set the display to path & surface in 2D, which overlays the optimization's path on a 2D contour plot of the response surface. Is this display consistent with your prediction of the response surface's shape? Set the display to path & surface in 3D, which overlays the optimization's path on a 3D surface plot. Is this display consistent with your prediction of the response surface's shape? What do your results suggest about the effectiveness of a sequential optimization?

**Exercise 3**. Using the first example, set the initial factor levels to (A,B) = (0,0) and count the number of steps it takes to reach the optimum response, and the number of times the algorithm switches between the two factors. Repeat for the other three examples. 
